TebLocalPlannerROS:

  #odom_topic: odom
  #map_frame: /odom

  teb_autosize: True
  dt_ref: 0.4
  dt_hysteresis: 0.05
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 5.0
  feasibility_check_no_poses: 4
  
  # Robot
  wheelbase: 0.3
  max_vel_x: 0.4
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "two_circles"
   #radius: 0.2 # for type "circular"
   #line_start: [-0.3, 0.0] # for type "line"
   #line_end: [0.3, 0.0] # for type "line"
   front_offset: 0.3 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

  # GoalTolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.3
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 20
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  inflation_dist: 0.3

  # Optimization
  no_inner_iterations: 4
  no_outer_iterations: 3
  weight_kinematics_forward_drive: 100
  weight_max_vel_x: 10